### PR TITLE
Add a package for obmd.

### PR DESCRIPTION
**Pull request by zenhack**
I decided to re-use this repository for packaging the obmd/hil-vpn stuff.

//cc @naved001, @ianballou

### CODE REVIEW

**Comment by zenhack** [comment]
@naved001, @ianballou, thoughts on this?

**Comment by naved001** [comment]
It slipped out of my mind, I'll review this asap.

**Review by naved001 — APPROVED** [review]
looks good to me, I was able to build obmd on a VM running fedora 29!

**Comment by zenhack** [comment]
Hm, I actually tried this out on a centos 7 VM after building on fc29 and got a failure:

```
[root@localhost vagrant]# rpm -i obmd-0.2-1.fc29.x86_64.rpm 
error: Failed dependencies:
	libc.so.6(GLIBC_2.28)(64bit) is needed by obmd-0.2-1.fc29.x86_64
```

I assume the package is implicitly depending on some base set of packages from fedora, though it shouldn't *actually* need libc to run. I'll poke around to see if there's a way to remove the dep.

**Comment by zenhack** [comment]
Fixed.

**Comment by zenhack** [comment]
Circling back to this now, amazing how easy it is to get sidetracked with other things when nobody pings you. IIRC we'd left off the vpnd stuff pretty close to useable, I'd like to finally finish that up. @naved001, can you try to poke someone about a second review on this?

**Pull request closed without merging**
